import type { Customer, Bottle, Cast, VisitRecord } from '@/types'

export const mockCasts: Cast[] = [
  { id: 'cast-1', name: '桜', ruby: 'さくら', memo: 'ナンバーワン。シャンパン担当。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-2', name: '愛', ruby: 'あい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-3', name: '蘭', ruby: 'らん', memo: '土日のみ出勤。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-4', name: '葵', ruby: 'あおい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-5', name: '凛', ruby: 'りん', memo: '新人。フォロー必要。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-6', name: '麻衣', ruby: 'まい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-7', name: '瑠璃', ruby: 'るり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-8', name: '奈々', ruby: 'なな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-9', name: '彩花', ruby: 'あやか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-10', name: '雪', ruby: 'ゆき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-11', name: '茉莉', ruby: 'まり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-12', name: '優香', ruby: 'ゆか', memo: '平日のみ。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-13', name: '心春', ruby: 'こはる', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-14', name: '結衣', ruby: 'ゆい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-15', name: '真琴', ruby: 'まこと', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-16', name: '里菜', ruby: 'りな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-17', name: '詩織', ruby: 'しおり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-18', name: '華', ruby: 'はな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-19', name: '千夏', ruby: 'ちなつ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-20', name: '明日香', ruby: 'あすか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-21', name: '紬', ruby: 'つむぎ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-22', name: '柚希', ruby: 'ゆずき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-23', name: '朱里', ruby: 'あかり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
]

export const mockCustomers: Customer[] = [
  {
    id: 'customer-1',
    name: '田中 一郎',
    ruby: 'たなか いちろう',
    nickname: 'たなちゃん',
    designatedCastIds: ['cast-1'],
    isAlert: false,
    alertReason: '',
    memo: 'VIPクライアント。高級シャンパン好み。',
    linkedCustomerIds: ['customer-4'],
    lastVisitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-2',
    name: '鈴木 健太',
    ruby: 'すずき けんた',
    nickname: 'すーさん',
    designatedCastIds: ['cast-2'],
    isAlert: true,
    alertReason: '支払いトラブルあり。過去に無断キャンセル2回。',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-3',
    name: '佐藤 大輔',
    ruby: 'さとう だいすけ',
    nickname: 'だいちゃん',
    designatedCastIds: [],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-4',
    name: '山田 誠',
    ruby: 'やまだ まこと',
    nickname: 'やまちゃん',
    designatedCastIds: ['cast-1', 'cast-2'],
    isAlert: false,
    alertReason: '',
    memo: 'ウィスキー好み。田中様の紹介。',
    linkedCustomerIds: ['customer-1'],
    lastVisitDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-5',
    name: '伊藤 博',
    ruby: 'いとう ひろし',
    nickname: 'ひろさん',
    designatedCastIds: ['cast-3'],
    isAlert: false,
    alertReason: '',
    memo: '誕生日：5月15日',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-6',
    name: '渡辺 隆',
    ruby: 'わたなべ たかし',
    nickname: 'わたさん',
    designatedCastIds: ['cast-2'],
    isAlert: false,
    alertReason: '',
    memo: '接待利用が多い。領収書必須。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-7',
    name: '中村 浩二',
    ruby: 'なかむら こうじ',
    nickname: 'こうちゃん',
    designatedCastIds: ['cast-4'],
    isAlert: false,
    alertReason: '',
    memo: 'ビール党。焼酎も可。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-8',
    name: '小林 正樹',
    ruby: 'こばやし まさき',
    nickname: 'まーくん',
    designatedCastIds: ['cast-5'],
    isAlert: false,
    alertReason: '',
    memo: '毎月第一金曜来店。',
    linkedCustomerIds: ['customer-9'],
    lastVisitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-9',
    name: '加藤 雄介',
    ruby: 'かとう ゆうすけ',
    nickname: 'ゆうすけ',
    designatedCastIds: ['cast-5'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: ['customer-8'],
    lastVisitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-10',
    name: '吉田 康夫',
    ruby: 'よしだ やすお',
    nickname: 'やっさん',
    designatedCastIds: ['cast-6'],
    isAlert: false,
    alertReason: '',
    memo: '日本酒専門。純米大吟醸のみ。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-11',
    name: '松本 哲也',
    ruby: 'まつもと てつや',
    nickname: 'てっちゃん',
    designatedCastIds: ['cast-7'],
    isAlert: false,
    alertReason: '',
    memo: 'ゴルフ好き。接待多め。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-12',
    name: '井上 修一',
    ruby: 'いのうえ しゅういち',
    nickname: 'しゅーさん',
    designatedCastIds: ['cast-3', 'cast-8'],
    isAlert: false,
    alertReason: '',
    memo: '誕生日：11月3日。ブランデー好き。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-13',
    name: '木村 俊介',
    ruby: 'きむら しゅんすけ',
    nickname: 'しゅんちゃん',
    designatedCastIds: ['cast-9'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-14',
    name: '林 大地',
    ruby: 'はやし だいち',
    nickname: 'だいちゃん',
    designatedCastIds: ['cast-10'],
    isAlert: true,
    alertReason: '過去に他のお客様とトラブルあり。座席配置に注意。',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-15',
    name: '清水 義雄',
    ruby: 'しみず よしお',
    nickname: 'よっちゃん',
    designatedCastIds: ['cast-11'],
    isAlert: false,
    alertReason: '',
    memo: 'ワイン専門。フランス産のみ。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-16',
    name: '橋本 信二',
    ruby: 'はしもと しんじ',
    nickname: 'しんちゃん',
    designatedCastIds: ['cast-12'],
    isAlert: false,
    alertReason: '',
    memo: '早めの時間帯希望。21時には退席。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-17',
    name: '岡田 光雄',
    ruby: 'おかだ みつお',
    nickname: 'みっちゃん',
    designatedCastIds: ['cast-13'],
    isAlert: false,
    alertReason: '',
    memo: '静かな席希望。カウンター禁止。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-18',
    name: '前田 竜也',
    ruby: 'まえだ たつや',
    nickname: 'りゅうちゃん',
    designatedCastIds: ['cast-14'],
    isAlert: false,
    alertReason: '',
    memo: 'スコッチウィスキー党。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-19',
    name: '藤田 宗一郎',
    ruby: 'ふじた そういちろう',
    nickname: 'ふじちゃん',
    designatedCastIds: ['cast-15'],
    isAlert: false,
    alertReason: '',
    memo: '誕生日：8月20日。シャンパン好き。',
    linkedCustomerIds: ['customer-20'],
    lastVisitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-20',
    name: '西村 隼人',
    ruby: 'にしむら はやと',
    nickname: 'はやちゃん',
    designatedCastIds: ['cast-16'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: ['customer-19'],
    lastVisitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-21',
    name: '高橋 健一',
    ruby: 'たかはし けんいち',
    nickname: 'けんさん',
    designatedCastIds: ['cast-4'],
    isAlert: false,
    alertReason: '',
    memo: 'テキーラ好み。ショットで飲む。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-22',
    name: '村上 浩',
    ruby: 'むらかみ ひろし',
    nickname: 'むーさん',
    designatedCastIds: ['cast-17'],
    isAlert: false,
    alertReason: '',
    memo: '常連。毎週土曜来店。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-23',
    name: '阿部 浩司',
    ruby: 'あべ こうじ',
    nickname: 'あべちゃん',
    designatedCastIds: ['cast-18'],
    isAlert: false,
    alertReason: '',
    memo: 'お酒弱め。ソフトドリンク多め。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-24',
    name: '石川 昌弘',
    ruby: 'いしかわ まさひろ',
    nickname: 'まさちゃん',
    designatedCastIds: ['cast-1'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-25',
    name: '上田 昭二',
    ruby: 'うえだ しょうじ',
    nickname: 'うえちゃん',
    designatedCastIds: ['cast-19'],
    isAlert: false,
    alertReason: '',
    memo: '経営者。大人数での来店多い。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-26',
    name: '河野 充',
    ruby: 'かわの みつる',
    nickname: 'みつさん',
    designatedCastIds: ['cast-20'],
    isAlert: false,
    alertReason: '',
    memo: 'ウォッカカクテル好き。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
]

export const mockBottles: Bottle[] = [
  {
    id: 'bottle-1',
    customerId: 'customer-1',
    name: 'ドンペリニヨン 2015',
    remaining: '100%',
    openedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-2',
    customerId: 'customer-1',
    name: 'バランタイン 17年',
    remaining: '50%',
    openedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-3',
    customerId: 'customer-1',
    name: 'ヘネシー XO',
    remaining: '10%',
    openedDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-4',
    customerId: 'customer-2',
    name: 'シーバスリーガル 18年',
    remaining: '75%',
    openedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-5',
    customerId: 'customer-4',
    name: 'サントリー響 21年',
    remaining: '30%',
    openedDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-6',
    customerId: 'customer-5',
    name: 'ジョニーウォーカー ブルーラベル',
    remaining: '100%',
    openedDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-7',
    customerId: 'customer-6',
    name: 'モエ・エ・シャンドン',
    remaining: '100%',
    openedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-8',
    customerId: 'customer-7',
    name: '山崎 12年',
    remaining: '60%',
    openedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-9',
    customerId: 'customer-8',
    name: 'マッカラン 18年',
    remaining: '80%',
    openedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-10',
    customerId: 'customer-10',
    name: '獺祭 二割三分',
    remaining: '50%',
    openedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-11',
    customerId: 'customer-12',
    name: 'レミーマルタン XO',
    remaining: '70%',
    openedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-12',
    customerId: 'customer-15',
    name: 'ペトリュス 2018',
    remaining: '100%',
    openedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-13',
    customerId: 'customer-16',
    name: 'ベルヴェデール ウォッカ',
    remaining: '40%',
    openedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-14',
    customerId: 'customer-18',
    name: 'グレンリベット 18年',
    remaining: '25%',
    openedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-15',
    customerId: 'customer-19',
    name: 'クリュッグ グランド キュヴェ',
    remaining: '100%',
    openedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-16',
    customerId: 'customer-22',
    name: 'アードベッグ 10年',
    remaining: '85%',
    openedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockVisitRecords: VisitRecord[] = [
  {
    id: 'visit-1',
    customerId: 'customer-1',
    visitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-1'],
    inStoreCastIds: ['cast-2'],
    bottlesOpened: ['bottle-1'],
    bottlesUsed: ['bottle-2'],
    memo: 'ドンペリ開封。大変ご機嫌でした。',
  },
  {
    id: 'visit-2',
    customerId: 'customer-1',
    visitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-1'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-2'],
    bottlesUsed: ['bottle-3'],
    memo: 'バランタイン開封。',
  },
  {
    id: 'visit-3',
    customerId: 'customer-2',
    visitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-2'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-4'],
    bottlesUsed: [],
    memo: '',
  },
  {
    id: 'visit-4',
    customerId: 'customer-4',
    visitDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-1'],
    inStoreCastIds: ['cast-3'],
    bottlesOpened: [],
    bottlesUsed: ['bottle-5'],
    memo: '響を使用。',
  },
  {
    id: 'visit-5',
    customerId: 'customer-5',
    visitDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-3'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-6'],
    bottlesUsed: [],
    memo: 'ブルーラベル開封。誕生日のお祝い。',
  },
  {
    id: 'visit-6',
    customerId: 'customer-6',
    visitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-2'],
    inStoreCastIds: ['cast-1'],
    bottlesOpened: ['bottle-7'],
    bottlesUsed: [],
    memo: '接待利用。領収書発行済。',
  },
  {
    id: 'visit-7',
    customerId: 'customer-7',
    visitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-4'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-8'],
    bottlesUsed: [],
    memo: '山崎開封。',
  },
  {
    id: 'visit-8',
    customerId: 'customer-8',
    visitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-5'],
    inStoreCastIds: ['cast-6'],
    bottlesOpened: ['bottle-9'],
    bottlesUsed: [],
    memo: '小林様・加藤様ご一緒に来店。',
  },
  {
    id: 'visit-9',
    customerId: 'customer-10',
    visitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-6'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-10'],
    bottlesUsed: [],
    memo: '獺祭開封。日本酒の話で盛り上がり。',
  },
  {
    id: 'visit-10',
    customerId: 'customer-12',
    visitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-3', 'cast-8'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-11'],
    bottlesUsed: [],
    memo: 'XO開封。',
  },
  {
    id: 'visit-11',
    customerId: 'customer-16',
    visitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-12'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-13'],
    bottlesUsed: [],
    memo: '早めにお帰り。',
  },
  {
    id: 'visit-12',
    customerId: 'customer-22',
    visitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-17'],
    inStoreCastIds: ['cast-18'],
    bottlesOpened: ['bottle-16'],
    bottlesUsed: [],
    memo: '毎週来店。今週も楽しんでいただいた。',
  },
]
